### ISSUE TITLE
Punkt 2.2 - kann ohne weitere kostenpflichtige ...

### ISSUE THREAD

**Issue by Wutze** [od-ms/datennutzungsklauseln-muster#4]
> 2.2 Die API folgt einem gängigen Standard (wie z. B. REST oder SOAP) und kann ohne weitere kostenpflichtige Entwicklungssysteme genutzt werden.

Mit der Begründung "ging nicht anders", wird das "kann" recht schnell umschifft. Deswegen sollte "kann" durch "muss" ersetzt werden.

Ich würde die betreffende Textstelle so formulieren:

[ ... ] muss durch jedes freie Entwicklungssystem genutzt werden können.

**Comment by od-ms** [comment]
Danke, diesen Punkt sollten wir in der Tat in der nächsten Version umformulieren.

**Comment by od-ms** [comment]
Vorschlag: "muss durch jedes freie und dem technischen Standard entsprchende Entwicklungssystem genutzt werden können."

**Comment by od-ms** [comment]
In Version 1.0 aufgenommen.
